Fix ts errors
1Green/faberpoke pull request #3
Opened 2021-03-01 16:14 UTC by RubenDeAndrade

Signed-off-by: Ruben De Andrade <ruben.deandrade@fabernovel.com>

- Fixed some ts errors
- Enable allowSyntheticDefaultImports in tsconfig

2021-03-01 16:54 UTC, williamgoulois approved these changes, later dismissed
Ok pour moi

2021-03-02 08:44 UTC, victorchabbert requested changes
Ce n'est pas une PR dupliqué de #4 ?

2021-03-02 08:44 UTC, victorchabbert commented on src/reportWebVitals.ts
> +    void import('web-vitals').then(({ getCLS, getFID, getFCP, getLCP, getTTFB }) => {
```suggestion
   import('web-vitals').then(({ getCLS, getFID, getFCP, getLCP, getTTFB }) => {
```
Ne pas utiliser void mais plutôt ajouter un catch

2021-03-02 08:57 UTC, RubenDeAndrade commented on src/reportWebVitals.ts
> +    void import('web-vitals').then(({ getCLS, getFID, getFCP, getLCP, getTTFB }) => {
J'ai supprimé le fichier finalement, car non utilisé.

2021-03-02 09:27 UTC, victorchabbert approved these changes

2021-03-04 16:13 UTC, closed without merging