Feature/pokemon card
1Green/faberpoke pull request #6
Opened 2021-03-04 16:29 UTC by williamgoulois

2021-03-05 11:18 UTC, RubenDeAndrade requested changes
Grosse P.R ! Un peu plus petite les prochaines fois ^^
Quelques petites modifs à faire, sinon gg

Manque plus que le design !

2021-03-05 11:18 UTC, RubenDeAndrade commented on src/pokemon/PokemonParser.tsx
> +}
Tu peux faire plus simple je pense, en déstructurant `jsonFromApi`.
const { name, order, ... } = jsonFromAPI;

ça évite de redéclarer des variables :)

2021-03-05 11:18 UTC, RubenDeAndrade commented on src/pokemon/buttonImg/buttonimg.module.css
> +.buttonimg {
Rajoute des `-` entre chaque mot pour que ce soit plus facile à lire :)

2021-03-05 11:18 UTC, RubenDeAndrade commented on src/pokemon/buttonImg/buttonimg.module.css
> +.imginside {
Pareil ici

2021-03-05 11:18 UTC, RubenDeAndrade commented on src/pokemon/statistic/PokemonStat.tsx
> +        <div className="pokemon-Stat-container">
mettre en minuscule la classe

2021-03-05 11:18 UTC, RubenDeAndrade commented on src/pokemon/type/pokemontype.module.css
> +.imgtype {
Pareil ici

2021-03-05 15:55 UTC, williamgoulois commented on src/pokemon/PokemonParser.tsx
> +}
Oui je les ai ajoutés au fur et à mesure sans penser à regrouper ! merci !

2021-03-05 15:57 UTC, williamgoulois commented on src/pokemon/buttonImg/buttonimg.module.css
> +.imginside {
J'ai tout passé en `camelCase` pour les noms (permet d'y accéder avec `styles.` et non `styles['']`)et j'ai modifié tous les CSS qui n'étaient pas des modules

2021-03-05 15:58 UTC, williamgoulois commented
Désolé pour la grosse PR oui j'aurai dû faire ça en plusieurs étapes !

2021-03-09 12:53 UTC, 1Green requested changes

2021-03-09 12:53 UTC, 1Green commented on src/pokemon/Pokemon.tsx
> +                            if (typeSlot.type.name !== 'unknown' && typeSlot.type.name !== 'shadow') {
Plutôt que de gérer cette logique ici et dans le composant PokemonType,  tu pourrais `filter` avant ton `map` !

2021-03-09 12:53 UTC, 1Green commented on src/pokemon/Pokemon.tsx
> +    const hasFemale: boolean = sprites[getSpritesKey('front', false, 'female')] !== null
Tu as besoin de préciser le type ici ?

2021-03-09 12:53 UTC, 1Green commented on src/pokemon/PokemonParser.tsx
> +        <Pokemon key={id} name={name} order={order} weight={weight} height={height} types={types} sprites={sprites} abilities={abilities} statistics={stats} />
```
const { id, stats, ...rest } = jsonFromApi
<Pokemon key={id} statistics={stats} {...rest} />
```

2021-03-09 12:53 UTC, 1Green commented on src/pokemon/PokemonParser.tsx
> +}
Tu as beaucoup de types identiques, ça mérite un peu de refacto ! 
Inutile de nommer différemment des types identiques, tu peux avoir un seul type nommé `Resource` par exemple avec ton name & url
Pareil pour tous tes types qui se répètent plus bas !

2021-03-09 12:53 UTC, 1Green commented on src/pokemon/ability/PokemonAbility.tsx
> +export type PokemonAbilityProps = {
export type PokemonAbilityProps = Readonly<{...}>

2021-03-09 12:53 UTC, 1Green commented on src/pokemon/buttonImage/ButtonImage.tsx
> +type Icons = { [key in IconKeys]: FC<SVGProps<SVGSVGElement>> }
On a déjà un composant `Icons`, il faudrait l'utiliser

2021-03-09 12:53 UTC, 1Green commented on src/pokemon/buttonImage/ButtonImage.tsx
> +  shiny?: boolean;
Ce composant devrait être bien plus générique.
La logique du gender / shiny devrait être gérée par le parent, et le composant devrait seulement recevoir une props `color`

2021-03-09 12:53 UTC, 1Green commented on src/pokemon/functions.ts
> +        gender==='female' ? 'female' : shiny ? undefined : 'default'
space

2021-03-09 12:53 UTC, 1Green commented on src/App.tsx
> +    <PokemonParser jsonFromApi={rawJson} />
Tu pourrais directement utiliser ton composant `<Pokemon/>` vu que PokemonParser ne fait rien pour le moment.

2021-03-09 13:15 UTC, williamgoulois commented on src/pokemon/Pokemon.tsx
> +                            if (typeSlot.type.name !== 'unknown' && typeSlot.type.name !== 'shadow') {
Oui c'est plus logique merci !

2021-03-09 13:15 UTC, williamgoulois commented on src/pokemon/Pokemon.tsx
> +    const hasFemale: boolean = sprites[getSpritesKey('front', false, 'female')] !== null
Heu non ça se voit mdr

2021-03-09 13:17 UTC, williamgoulois commented on src/pokemon/PokemonParser.tsx
> +        <Pokemon key={id} name={name} order={order} weight={weight} height={height} types={types} sprites={sprites} abilities={abilities} statistics={stats} />
Je ne pense pas directement à cet opérateur merci !

2021-03-09 14:06 UTC, williamgoulois commented on src/pokemon/PokemonParser.tsx
> +}
Tous les types ont été générés de façon automatique avec [Json2ts](http://json2ts.com/) mais je vais faire un peu de refacto !

2021-03-09 14:36 UTC, williamgoulois commented on src/pokemon/functions.ts
> +        gender==='female' ? 'female' : shiny ? undefined : 'default'
L'API n'est malheureusement pas consistante sur le naming des sprites:
front_shiny pour le male shiny (et nom front_shiny_default) donc ça rend les ternaires un peu plus exotiques !

2021-03-09 14:42 UTC, williamgoulois commented on src/App.tsx
> +    <PokemonParser jsonFromApi={rawJson} />
J'ai supprimé le RFC PokemonParser et conservé que les interfaces

2021-03-09 16:01 UTC, williamgoulois commented on src/pokemon/buttonImage/ButtonImage.tsx
> +  shiny?: boolean;
j'ai passé la logique au parent

2021-03-09 16:02 UTC, williamgoulois commented on src/pokemon/buttonImage/ButtonImage.tsx
> +type Icons = { [key in IconKeys]: FC<SVGProps<SVGSVGElement>> }
J'ai ajouté mes svg au composant `Icon` existant

2021-03-09 16:04 UTC, williamgoulois commented on src/pokemon/ability/PokemonAbility.tsx
> +export type PokemonAbilityProps = {
J'ai essayé de passer les props de cette manière mais lorsque je fais :
```typescript
export type PokemonProps = Readonly<PokeApiResponse>;

export function Pokemon({ name, order, weight, height, types, sprites }: PokemonProps) {
  order = 24; // aucune erreur n'est levée par eslint ou typescript
```

2021-03-09 16:34 UTC, williamgoulois commented on src/pokemon/ability/PokemonAbility.tsx
> +export type PokemonAbilityProps = {
J'en ai parlé avec Victor il m'a dit qu'il ne s'en servait jamais ! Je n'ai pas trouvé d'exemple de code avec une utilisation dans les props d'un RFC sur le net

2021-03-10 15:31 UTC, 1Green approved these changes

2021-03-10 15:31 UTC, 1Green commented on src/pokemon/functions.ts
> +        gender==='female' ? 'female' : shiny ? undefined : 'default'
Je disais juste qu'il manquait un espace :p `gender === 'female'`

2021-03-10 15:37 UTC, RubenDeAndrade approved these changes

2021-03-10 15:58 UTC, merged