Feature/pagination
1Green/faberpoke pull request #7
Opened 2021-03-05 10:24 UTC by RubenDeAndrade

I created a pagination component to navigate between list.
We can give it list length, page limit, and it displays the appropriate pagination.

When current page changed, a callback is fired to parent so we can display new elements in our list.

# Screenshot

<img width="269" alt="Capture d’écran 2021-03-05 à 11 18 44" src="https://user-images.githubusercontent.com/28705409/110102376-014f9280-7da5-11eb-8bf8-b3efba067475.png">

# Test

`yarn storybook`

2021-03-05 16:43 UTC, williamgoulois commented
Code un peu complexe à lire et comprendre, j'ai pu tester sur storybook et je trouve que l'UX est bizarre pour une pagination (notamment quand on passe de la page 66 à 67 si on clique sur Next le bouton Next devient 67)

On changera l'UX plus tard

2021-03-05 16:51 UTC, williamgoulois requested changes

2021-03-05 16:51 UTC, williamgoulois commented on src/stories/pagination/Pagination.tsx
> +                    ['page-link-wrapper--active']: currentPage === page
Warning de eslint : 

`Unnecessarily computed property ['page-link-wrapper--active'] found. eslint(no-useless-computed-key)`

```typescript
 'page-link-wrapper--active': currentPage === page
```

2021-03-05 16:51 UTC, williamgoulois commented on src/stories/pagination/Pagination.tsx
> +    }, [currentPage]);
Warning 

`React Hook useEffect has missing dependencies: 'onPageChanged', 'pageLimit', 'totalPages', and 'totalRecords'. Either include them or remove the dependency array. If 'onPageChanged' changes too often, find the parent component that defines it and wrap that definition in useCallback. eslint(react-hooks/exhaustive-deps)`

```typescript
}, [currentPage, onPageChanged, pageLimit, totalPages, totalRecords]);
```

2021-03-09 12:10 UTC, 1Green approved these changes, later dismissed

2021-03-09 12:10 UTC, 1Green commented on src/stories/pagination/Pagination.tsx
> +const RIGHT_PAGE = 'RIGHT';
Tu peux essayer d'utiliser un [enum](https://www.typescriptlang.org/docs/handbook/enums.html) en typescript ici !

2021-03-09 12:10 UTC, 1Green commented on src/stories/pagination/Pagination.stories.tsx
> +}
New line

2021-03-09 12:10 UTC, 1Green commented
Deux petites remarques mais le reste semble ok

2021-03-10 09:14 UTC, williamgoulois approved these changes, later dismissed

2021-03-10 15:31 UTC, 1Green approved these changes, later dismissed

2021-03-10 16:01 UTC, 1Green approved these changes

2021-03-10 16:02 UTC, williamgoulois approved these changes

2021-03-10 16:02 UTC, merged