Feature/search input
1Green/faberpoke pull request #8
Opened 2021-03-05 13:42 UTC by RubenDeAndrade

I created a SearchInput component that will be used for our Pokemon search section.

# Screenshot

<img width="235" alt="Capture d’écran 2021-03-05 à 13 29 06" src="https://user-images.githubusercontent.com/28705409/110123182-dbd08200-7dc0-11eb-8544-296d8a04336d.png">

# Test

`yarn storybook`

2021-03-05 17:05 UTC, williamgoulois requested changes

2021-03-05 17:05 UTC, williamgoulois commented on src/stories/inputSearch/InputSearch.tsx
> +import Icon from "../icon/Icon";
Ton dossier s'appelle Icon et non icon

passe le nom de dossier en lowercase ou change l'import

2021-03-09 12:04 UTC, 1Green reviewed
On peut renommer /stories en /components au passage !

2021-03-09 12:04 UTC, 1Green commented on src/stories/inputSearch/InputSearch.tsx
> +    onChange?: (text: string) => void;
Pourquoi avoir un onChange optionel ? Ton input ne pourra jamais fonctionner sans.

2021-03-09 12:04 UTC, 1Green commented on src/stories/inputSearch/InputSearch.stories.tsx
> +};
new line

2021-03-09 12:04 UTC, 1Green commented on src/stories/inputSearch/InputSearch.tsx
> +                onMouseEnter={() => setClearButtonEnable(true)}
On ne peut pas gérer ça en CSS avec un `:hover` ?

2021-03-10 09:15 UTC, williamgoulois approved these changes

2021-03-10 15:32 UTC, 1Green approved these changes

2021-03-10 15:36 UTC, merged